// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/defect": {
            "get": {
                "description": "collect information of some defects",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Defect"
                ],
                "summary": "collect information of some defects",
                "parameters": [
                    {
                        "type": "string",
                        "description": "collect defects after the date",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/app.CollectDefectsDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/defect/bulletin": {
            "post": {
                "description": "generate security bulletin for some defects",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Defect"
                ],
                "summary": "generate security bulletin for some defects",
                "parameters": [
                    {
                        "description": "body of some issue number",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.bulletinRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.CollectDefectsDTO": {
            "type": "object",
            "properties": {
                "component": {
                    "type": "string"
                },
                "issue_id": {
                    "type": "string"
                },
                "score": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "controller.bulletinRequest": {
            "type": "object",
            "required": [
                "issue_number"
            ],
            "properties": {
                "issue_number": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
