// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/defect": {
            "post": {
                "description": "add or update a defect",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Defect"
                ],
                "summary": "add or update a defect",
                "parameters": [
                    {
                        "description": "body of a defect",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.defectRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "controller.defectRequest": {
            "type": "object",
            "required": [
                "abi",
                "affected_version",
                "component",
                "description",
                "guidance_url",
                "influence",
                "issue_number",
                "issue_org",
                "issue_repo",
                "issue_status",
                "kernel",
                "reference_url",
                "severity_level",
                "system_version"
            ],
            "properties": {
                "abi": {
                    "type": "string"
                },
                "affected_version": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "component": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "guidance_url": {
                    "type": "string"
                },
                "influence": {
                    "type": "string"
                },
                "issue_number": {
                    "type": "string"
                },
                "issue_org": {
                    "type": "string"
                },
                "issue_repo": {
                    "type": "string"
                },
                "issue_status": {
                    "type": "string"
                },
                "kernel": {
                    "type": "string"
                },
                "reference_url": {
                    "type": "string"
                },
                "severity_level": {
                    "type": "string"
                },
                "system_version": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
